[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/anthropic/*"
  to = "/.netlify/functions/anthropic"
  status = 200
  force = true

[[redirects]]
  from = "/api/fal"
  to = "/.netlify/functions/fal"
  status = 200
  force = true

[[redirects]]
  from = "/api/gpt-image"
  to = "/.netlify/functions/gpt-image"
  status = 200
  force = true
